import type { ConversationMessage, ConversationSnapshot } from "./types.js";

// Reduces a Claude Code session transcript (one JSON object per line) to the
// human conversation: the captain's typed messages and the assistant's reply
// to each. Tool calls, tool results, thinking, hook and system injections,
// slash-command wrappers, skill bodies and "doing X now" narration are dropped.
//
// The transcript is split into segments. A segment starts at anything that
// makes the assistant take a new turn — a captain message, or an injection
// such as a background-task notification — and holds the assistant blocks
// that follow. Each segment contributes at most one reply: the text the
// assistant ends the turn with.

/** A text block shorter than this is narration unless it ends the turn. */
const SUBSTANTIVE_CHARS = 280;
const NO_REPLY_TEXTS = new Set(["No response requested.", "(no content)"]);

type Json = Record<string, unknown>;

interface AssistantText {
  id: string;
  text: string;
  timestamp?: string;
}

interface Segment {
  id: string;
  /** Text blocks since the last tool call; the candidate final reply. */
  trailing: AssistantText[];
  /** Longest text seen anywhere in the segment, used when the turn never settles. */
  longest?: AssistantText;
  settled: boolean;
  /** The assistant has produced anything at all in this segment. */
  started: boolean;
  /** What the assistant is doing now, in a few plain words (see activityOf). */
  activity?: { text: string; rank: number };
  /** Started by firstmate's supervision (a watcher wake, an operational input), not by the captain. */
  wake?: boolean;
}

function isRecord(value: unknown): value is Json {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

function stringField(record: Json, key: string): string | undefined {
  const value = record[key];
  return typeof value === "string" ? value : undefined;
}

function contentBlocks(content: unknown): Json[] {
  return Array.isArray(content) ? content.filter(isRecord) : [];
}

const INJECTION_PREFIXES = [
  "<task-notification>",
  "<local-command-",
  "<bash-input>",
  "<bash-stdout>",
  "<bash-stderr>",
  "<user-memory-input>",
  "[Request interrupted by user",
  "Caveat: The messages below were generated by the user while running local commands",
  "Base directory for this skill:",
  "This session is being continued from a previous conversation",
];

function stripTagged(text: string, tag: string): string {
  return text.replace(new RegExp(`<${tag}>[\\s\\S]*?</${tag}>`, "g"), "");
}

function rewritePasted(text: string): string {
  return text.replace(/\s*<pasted_content[^>]*>([\s\S]*?)<\/pasted_content[^>]*>\s*/g, (_match, body: string) => {
    const inner = body.replace(/^\n+|\n+$/g, "");
    return `\n\n\`\`\`\n${inner}\n\`\`\`\n\n`;
  });
}

/** `<command-name>/x</command-name>…<command-args>y</command-args>` → "/x y"; bare housekeeping commands vanish. */
function rewriteCommand(text: string): string | null {
  const name = /<command-name>([\s\S]*?)<\/command-name>/.exec(text)?.[1]?.trim();
  if (!name) return text;
  const args = /<command-args>([\s\S]*?)<\/command-args>/.exec(text)?.[1]?.trim() ?? "";
  if (!args) return null;
  return `${name.startsWith("/") ? name : `/${name}`} ${args}`;
}

/**
 * Returns what the captain actually typed, or null when the text is machinery
 * (injections, reminders, local command output, empty wrappers).
 */
export function cleanCaptainText(raw: string): string | null {
  let text = raw.trim();
  if (!text) return null;
  if (INJECTION_PREFIXES.some((prefix) => text.startsWith(prefix))) return null;
  const command = rewriteCommand(text);
  if (command === null) return null;
  text = command;
  text = stripTagged(text, "system-reminder");
  text = rewritePasted(text);
  text = text.replace(/\n{3,}/g, "\n\n").trim();
  return text || null;
}

/**
 * Id of the n-th image block in the transcript line starting at byte
 * `offset`. The bytes stay in the transcript; the source reads them back on
 * demand (see ClaudeCodeTranscriptSource.image).
 */
export function transcriptImageId(offset: number, n: number): string {
  return `t${offset}.${n}`;
}

function imageBlocks(content: unknown): Json[] {
  return contentBlocks(content).filter((block) => block.type === "image");
}

/** The n-th pasted image of a captain entry (a user message or a queued command), as base64. */
export function captainImageAt(entry: unknown, n: number): { mediaType: string; data: string } | null {
  if (!isRecord(entry)) return null;
  const content = entry.type === "user" && isRecord(entry.message)
    ? entry.message.content
    : entry.type === "attachment" && isRecord(entry.attachment)
      ? entry.attachment.prompt
      : undefined;
  const source = imageBlocks(content)[n]?.source;
  if (!isRecord(source) || source.type !== "base64") return null;
  const mediaType = stringField(source, "media_type");
  const data = stringField(source, "data");
  return mediaType && data ? { mediaType, data } : null;
}

/**
 * What the captain typed in a user content value (string or blocks), plus
 * the ids of images he pasted; null when there is neither. Claude Code puts
 * an "[Image #N]" marker in the text for each pasted image, in order; markers
 * whose image is shown are dropped from the text.
 */
function captainContentOf(content: unknown, offset?: number): { text: string; images: string[] } | null {
  if (typeof content === "string") {
    const text = cleanCaptainText(content);
    return text ? { text, images: [] } : null;
  }
  const blocks = contentBlocks(content);
  if (blocks.some((block) => block.type === "tool_result")) return null;
  const joined = blocks
    .filter((block) => block.type === "text")
    .map((block) => stringField(block, "text") ?? "")
    .join("\n\n");
  const count = offset === undefined ? 0 : imageBlocks(content).length;
  const images = Array.from({ length: count }, (_unused, n) => transcriptImageId(offset!, n));
  let text = joined.trim() ? cleanCaptainText(joined) : "";
  if (text === null) return null;
  let left = images.length;
  text = text.replace(/\[Image #\d+\]\s?/g, (marker) => (left-- > 0 ? "" : marker)).trim();
  if (!text && images.length === 0) return blocks.some((block) => block.type === "image") ? { text: "*[image]*", images } : null;
  return { text, images };
}

/** An operational input firstmate typed itself. */
const OPERATIONAL_INPUT = /^\u2063?FIRSTMATE_OP:/;
/** A watcher (Stop-hook) wake, which only machinery injects. */
const WATCHER_WAKE = /firstmate watcher wake\b/;

/** Firstmate's supervision turns: a watcher wake from machinery, or an operational input. */
function isSupervisionWake(content: unknown, machine: boolean): boolean {
  const text = typeof content === "string"
    ? content
    : contentBlocks(content).filter((block) => block.type === "text").map((block) => stringField(block, "text") ?? "").join("\n");
  return OPERATIONAL_INPUT.test(text.trimStart()) || (machine && WATCHER_WAKE.test(text));
}

function originKind(record: Json): string | undefined {
  const origin = record.origin;
  return isRecord(origin) ? stringField(origin, "kind") : undefined;
}

function captainMessage(id: string, said: { text: string; images: string[] }, timestamp?: string): ConversationMessage {
  return {
    id,
    role: "user",
    text: said.text,
    ...(said.images.length ? { images: said.images } : {}),
    ...(timestamp ? { timestamp } : {}),
  };
}

/** One short plain line: no Markdown, no salutation, no trailing colon. */
function activityLine(raw: string): string | null {
  const line = raw
    .split("\n")[0]!
    .replace(/`([^`]*)`/g, "$1")
    .replace(/\*\*([^*]+)\*\*/g, "$1")
    .replace(/^(?:captain|george)[,!:]\s*/i, "")
    .replace(/[:…]+$/, "")
    .replace(/\s+/g, " ")
    .trim();
  if (line.length < 3) return null;
  const text = line.charAt(0).toUpperCase() + line.slice(1);
  return text.length > 80 ? `${text.slice(0, 79).trimEnd()}…` : text;
}

/**
 * What a tool call says about the current step, ranked: the assistant's
 * own task list (3) and delegated work (2) over a shell step's description
 * (1). Reads, edits and searches say nothing worth showing.
 */
function activityOf(block: Json): { text: string; rank: number } | null {
  const input = isRecord(block.input) ? block.input : {};
  const name = stringField(block, "name") ?? "";
  if (name === "TodoWrite" && Array.isArray(input.todos)) {
    const doing = input.todos.filter(isRecord).find((todo) => todo.status === "in_progress");
    const text = doing && (stringField(doing, "activeForm") ?? stringField(doing, "content"));
    return text && activityLine(text) ? { text: activityLine(text)!, rank: 3 } : null;
  }
  const active = stringField(input, "activeForm");
  if (active && activityLine(active)) return { text: activityLine(active)!, rank: 3 };
  const description = stringField(input, "description");
  if (!description || !activityLine(description)) return null;
  if (name === "Agent" || name === "Task") return { text: activityLine(description)!, rank: 2 };
  if (name === "Bash") return { text: activityLine(description)!, rank: 1 };
  return null;
}

/**
 * Incrementally folds transcript entries into the visible conversation.
 * Push entries in file order; read `snapshot()` whenever needed.
 */
export class TranscriptConversation {
  private readonly finished: ConversationMessage[] = [];
  private segment: Segment | null = null;
  private lastActivity?: string;
  private segmentCount = 0;
  private context?: { tokens: number; model: string };
  private maxContext = 0;

  /**
   * Parses one JSONL line; malformed lines (e.g. a torn write) are ignored.
   * With the line's byte `offset`, pasted images become viewable.
   */
  pushLine(line: string, offset?: number): void {
    // Tool results carry most of a transcript's bytes and never matter here;
    // the unescaped marker cannot occur inside a JSON string value, and an
    // entry carrying a tool result is never a captain message.
    if (line.includes('"type":"tool_result"')) {
      this.touch(line);
      return;
    }
    let entry: unknown;
    try {
      entry = JSON.parse(line);
    } catch {
      return;
    }
    if (isRecord(entry)) this.push(entry, offset);
  }

  private touch(line: string): void {
    const match = /"timestamp":"([^"]+)"/.exec(line);
    if (match) this.lastActivity = match[1];
  }

  push(entry: Json, offset?: number): void {
    if (entry.isSidechain === true) return;
    const timestamp = stringField(entry, "timestamp");
    if (timestamp) this.lastActivity = timestamp;

    switch (entry.type) {
      case "user":
        this.pushUser(entry, timestamp, offset);
        return;
      case "assistant":
        this.pushAssistant(entry, timestamp);
        return;
      case "attachment":
        this.pushAttachment(entry, timestamp, offset);
        return;
      default:
        return;
    }
  }

  private pushUser(entry: Json, timestamp?: string, offset?: number): void {
    const message = isRecord(entry.message) ? entry.message : undefined;
    if (!message) return;
    const blocks = contentBlocks(message.content);
    // A tool result continues the assistant's turn; it is not a new prompt.
    if (blocks.some((block) => block.type === "tool_result")) return;
    if (entry.isMeta === true) return;

    const id = stringField(entry, "uuid") ?? `user-${this.finished.length}`;
    const kind = originKind(entry);
    const machine = kind !== undefined && kind !== "human";
    const wake = isSupervisionWake(message.content, machine);
    const said = entry.isCompactSummary === true || wake || machine
      ? null
      : captainContentOf(message.content, offset);
    this.startSegment(id, wake);
    if (said) this.finished.push(captainMessage(id, said, timestamp));
  }

  /** Messages the captain sends while the assistant works arrive as queued_command attachments. */
  private pushAttachment(entry: Json, timestamp?: string, offset?: number): void {
    const attachment = isRecord(entry.attachment) ? entry.attachment : undefined;
    if (!attachment || attachment.type !== "queued_command") return;
    if (attachment.commandMode !== undefined && attachment.commandMode !== "prompt") return;
    const kind = originKind(attachment);
    if (kind !== undefined && kind !== "human") return;
    const said = captainContentOf(attachment.prompt, offset);
    if (!said) return;
    const id = stringField(attachment, "source_uuid") ?? stringField(entry, "uuid") ?? `queued-${this.finished.length}`;
    this.startSegment(id);
    this.finished.push(captainMessage(id, said, timestamp));
  }

  private pushAssistant(entry: Json, timestamp?: string): void {
    if (entry.isApiErrorMessage === true) return;
    const message = isRecord(entry.message) ? entry.message : undefined;
    if (!message || message.model === "<synthetic>") return;
    this.noteUsage(message);
    if (!this.segment) this.startSegment(stringField(entry, "uuid") ?? "start");
    const segment = this.segment!;
    segment.started = true;

    const uuid = stringField(entry, "uuid") ?? `${segment.id}-${segment.trailing.length}`;
    contentBlocks(message.content).forEach((block, index) => {
      if (block.type === "tool_use" || block.type === "server_tool_use") {
        // Text said just before a tool call is the assistant naming its next step.
        const said = segment.trailing.at(-1);
        const narration = said && said.text.length < SUBSTANTIVE_CHARS ? activityLine(said.text) : null;
        if (narration) segment.activity = { text: narration, rank: 3 };
        const step = activityOf(block);
        if (step && step.rank >= (segment.activity?.rank ?? 0)) segment.activity = step;
        segment.trailing = [];
        segment.settled = false;
        return;
      }
      if (block.type !== "text") return;
      const text = (stringField(block, "text") ?? "").trim();
      if (!text || NO_REPLY_TEXTS.has(text)) return;
      const piece: AssistantText = { id: `${uuid}:${index}`, text, ...(timestamp ? { timestamp } : {}) };
      segment.trailing.push(piece);
      if (!segment.longest || text.length > segment.longest.text.length) segment.longest = piece;
    });
    if (message.stop_reason === "end_turn" || message.stop_reason === "stop_sequence") segment.settled = true;
  }

  /** Context in use = everything the model read for this turn: fresh, cached and newly cached input. */
  private noteUsage(message: Json): void {
    const usage = isRecord(message.usage) ? message.usage : undefined;
    if (!usage) return;
    const count = (key: string) => (typeof usage[key] === "number" ? (usage[key] as number) : 0);
    const tokens = count("input_tokens") + count("cache_read_input_tokens") + count("cache_creation_input_tokens");
    if (tokens <= 0) return;
    this.context = { tokens, model: stringField(message, "model") ?? "" };
    this.maxContext = Math.max(this.maxContext, tokens);
  }

  private startSegment(id: string, wake = false): void {
    this.closeSegment();
    this.segmentCount += 1;
    this.segment = { id: `${id}#${this.segmentCount}`, trailing: [], settled: false, started: false, ...(wake ? { wake } : {}) };
  }

  private closeSegment(): void {
    if (!this.segment) return;
    const reply = this.replyOf(this.segment, true);
    if (reply) this.finished.push(reply);
    this.segment = null;
  }

  /**
   * The reply a segment shows. A settled turn shows the text it ended on.
   * A turn cut off before settling (interrupted, or the captain spoke
   * mid-turn) shows its longest text only if that text is substantive;
   * short progress notes never surface.
   */
  private replyOf(segment: Segment, closed: boolean): ConversationMessage | null {
    let pieces: AssistantText[] = [];
    if (segment.settled && segment.trailing.length > 0) pieces = segment.trailing;
    else if (closed && segment.longest && segment.longest.text.length >= SUBSTANTIVE_CHARS) pieces = [segment.longest];
    if (pieces.length === 0) return null;
    const last = pieces[pieces.length - 1]!;
    return {
      id: `reply:${segment.id}`,
      role: "assistant",
      text: pieces.map((piece) => piece.text).join("\n\n"),
      ...(last.timestamp ? { timestamp: last.timestamp } : {}),
      ...(segment.wake ? { wake: true } : {}),
    };
  }

  snapshot(): ConversationSnapshot {
    const messages = [...this.finished];
    const open = this.segment;
    const reply = open ? this.replyOf(open, false) : null;
    if (reply) messages.push(reply);
    const lastIsUser = this.finished.length > 0 && this.finished[this.finished.length - 1]!.role === "user";
    const working = open !== null && !reply && (open.started || lastIsUser);
    return {
      messages,
      working,
      ...(working && open?.activity ? { activity: open.activity.text } : {}),
      ...(this.lastActivity ? { lastActivity: this.lastActivity } : {}),
      ...(this.context ? { context: { tokens: this.context.tokens, window: contextWindow(this.context.model, this.maxContext) } } : {}),
    };
  }
}

/**
 * The model's context window. Claude 5 models in Claude Code run with 1M;
 * a session that has already gone past 200k proves it is 1M too.
 * FLYD_VIEW_CONTEXT_WINDOW overrides.
 */
export function contextWindow(model: string, maxSeen: number, env: NodeJS.ProcessEnv = process.env): number {
  const override = Number(env.FLYD_VIEW_CONTEXT_WINDOW);
  if (Number.isInteger(override) && override > 0) return override;
  if (/\[1m\]/i.test(model) || /^claude-(opus|sonnet|fable|haiku)-5/.test(model) || maxSeen > 200_000) return 1_000_000;
  return 200_000;
}

/** Convenience for whole-file reads and tests. */
export function conversationFromLines(lines: Iterable<string>): ConversationSnapshot {
  const conversation = new TranscriptConversation();
  for (const line of lines) if (line.trim()) conversation.pushLine(line);
  return conversation.snapshot();
}
