import type { ConversationMessage, ConversationSnapshot } from "./types.js";

// Reduces a Claude Code session transcript (one JSON object per line) to the
// human conversation: the captain's typed messages and the assistant's reply
// to each. Tool calls, tool results, thinking, hook and system injections,
// slash-command wrappers, skill bodies and "doing X now" narration are dropped.
//
// The transcript is split into segments. A segment starts at anything that
// makes the assistant take a new turn — a captain message, or an injection
// such as a background-task notification — and holds the assistant blocks
// that follow. Each segment contributes at most one reply: the text the
// assistant ends the turn with.

/** A text block shorter than this is narration unless it ends the turn. */
const SUBSTANTIVE_CHARS = 280;
const NO_REPLY_TEXTS = new Set(["No response requested.", "(no content)"]);

type Json = Record<string, unknown>;

interface AssistantText {
  id: string;
  text: string;
  timestamp?: string;
}

interface Segment {
  id: string;
  /** Text blocks since the last tool call; the candidate final reply. */
  trailing: AssistantText[];
  /** Longest text seen anywhere in the segment, used when the turn never settles. */
  longest?: AssistantText;
  settled: boolean;
  /** The assistant has produced anything at all in this segment. */
  started: boolean;
}

function isRecord(value: unknown): value is Json {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

function stringField(record: Json, key: string): string | undefined {
  const value = record[key];
  return typeof value === "string" ? value : undefined;
}

function contentBlocks(content: unknown): Json[] {
  return Array.isArray(content) ? content.filter(isRecord) : [];
}

const INJECTION_PREFIXES = [
  "<task-notification>",
  "<local-command-",
  "<bash-input>",
  "<bash-stdout>",
  "<bash-stderr>",
  "<user-memory-input>",
  "[Request interrupted by user",
  "Caveat: The messages below were generated by the user while running local commands",
  "Base directory for this skill:",
  "This session is being continued from a previous conversation",
];

function stripTagged(text: string, tag: string): string {
  return text.replace(new RegExp(`<${tag}>[\\s\\S]*?</${tag}>`, "g"), "");
}

function rewritePasted(text: string): string {
  return text.replace(/\s*<pasted_content[^>]*>([\s\S]*?)<\/pasted_content[^>]*>\s*/g, (_match, body: string) => {
    const inner = body.replace(/^\n+|\n+$/g, "");
    return `\n\n\`\`\`\n${inner}\n\`\`\`\n\n`;
  });
}

/** `<command-name>/x</command-name>…<command-args>y</command-args>` → "/x y"; bare housekeeping commands vanish. */
function rewriteCommand(text: string): string | null {
  const name = /<command-name>([\s\S]*?)<\/command-name>/.exec(text)?.[1]?.trim();
  if (!name) return text;
  const args = /<command-args>([\s\S]*?)<\/command-args>/.exec(text)?.[1]?.trim() ?? "";
  if (!args) return null;
  return `${name.startsWith("/") ? name : `/${name}`} ${args}`;
}

/**
 * Returns what the captain actually typed, or null when the text is machinery
 * (injections, reminders, local command output, empty wrappers).
 */
export function cleanCaptainText(raw: string): string | null {
  let text = raw.trim();
  if (!text) return null;
  if (INJECTION_PREFIXES.some((prefix) => text.startsWith(prefix))) return null;
  const command = rewriteCommand(text);
  if (command === null) return null;
  text = command;
  text = stripTagged(text, "system-reminder");
  text = rewritePasted(text);
  text = text.replace(/\n{3,}/g, "\n\n").trim();
  return text || null;
}

/** Text the captain typed in a user content value (string or blocks); null if none. */
function captainTextOf(content: unknown): string | null {
  if (typeof content === "string") return cleanCaptainText(content);
  const blocks = contentBlocks(content);
  if (blocks.some((block) => block.type === "tool_result")) return null;
  const texts = blocks
    .filter((block) => block.type === "text")
    .map((block) => stringField(block, "text") ?? "");
  const hasImage = blocks.some((block) => block.type === "image");
  const joined = texts.join("\n\n");
  if (!joined.trim()) return hasImage ? "*[image]*" : null;
  return cleanCaptainText(joined);
}

function originKind(record: Json): string | undefined {
  const origin = record.origin;
  return isRecord(origin) ? stringField(origin, "kind") : undefined;
}

/**
 * Incrementally folds transcript entries into the visible conversation.
 * Push entries in file order; read `snapshot()` whenever needed.
 */
export class TranscriptConversation {
  private readonly finished: ConversationMessage[] = [];
  private segment: Segment | null = null;
  private lastActivity?: string;
  private segmentCount = 0;

  /** Parses one JSONL line; malformed lines (e.g. a torn write) are ignored. */
  pushLine(line: string): void {
    // Tool results carry most of a transcript's bytes and never matter here;
    // the unescaped marker cannot occur inside a JSON string value, and an
    // entry carrying a tool result is never a captain message.
    if (line.includes('"type":"tool_result"')) {
      this.touch(line);
      return;
    }
    let entry: unknown;
    try {
      entry = JSON.parse(line);
    } catch {
      return;
    }
    if (isRecord(entry)) this.push(entry);
  }

  private touch(line: string): void {
    const match = /"timestamp":"([^"]+)"/.exec(line);
    if (match) this.lastActivity = match[1];
  }

  push(entry: Json): void {
    if (entry.isSidechain === true) return;
    const timestamp = stringField(entry, "timestamp");
    if (timestamp) this.lastActivity = timestamp;

    switch (entry.type) {
      case "user":
        this.pushUser(entry, timestamp);
        return;
      case "assistant":
        this.pushAssistant(entry, timestamp);
        return;
      case "attachment":
        this.pushAttachment(entry, timestamp);
        return;
      default:
        return;
    }
  }

  private pushUser(entry: Json, timestamp?: string): void {
    const message = isRecord(entry.message) ? entry.message : undefined;
    if (!message) return;
    const blocks = contentBlocks(message.content);
    // A tool result continues the assistant's turn; it is not a new prompt.
    if (blocks.some((block) => block.type === "tool_result")) return;
    if (entry.isMeta === true) return;

    const id = stringField(entry, "uuid") ?? `user-${this.finished.length}`;
    const kind = originKind(entry);
    const text = entry.isCompactSummary === true || (kind !== undefined && kind !== "human")
      ? null
      : captainTextOf(message.content);
    this.startSegment(id);
    if (text) this.finished.push({ id, role: "user", text, ...(timestamp ? { timestamp } : {}) });
  }

  /** Messages the captain sends while the assistant works arrive as queued_command attachments. */
  private pushAttachment(entry: Json, timestamp?: string): void {
    const attachment = isRecord(entry.attachment) ? entry.attachment : undefined;
    if (!attachment || attachment.type !== "queued_command") return;
    if (attachment.commandMode !== undefined && attachment.commandMode !== "prompt") return;
    const kind = originKind(attachment);
    if (kind !== undefined && kind !== "human") return;
    const text = captainTextOf(attachment.prompt);
    if (!text) return;
    const id = stringField(attachment, "source_uuid") ?? stringField(entry, "uuid") ?? `queued-${this.finished.length}`;
    this.startSegment(id);
    this.finished.push({ id, role: "user", text, ...(timestamp ? { timestamp } : {}) });
  }

  private pushAssistant(entry: Json, timestamp?: string): void {
    if (entry.isApiErrorMessage === true) return;
    const message = isRecord(entry.message) ? entry.message : undefined;
    if (!message || message.model === "<synthetic>") return;
    if (!this.segment) this.startSegment(stringField(entry, "uuid") ?? "start");
    const segment = this.segment!;
    segment.started = true;

    const uuid = stringField(entry, "uuid") ?? `${segment.id}-${segment.trailing.length}`;
    contentBlocks(message.content).forEach((block, index) => {
      if (block.type === "tool_use" || block.type === "server_tool_use") {
        segment.trailing = [];
        segment.settled = false;
        return;
      }
      if (block.type !== "text") return;
      const text = (stringField(block, "text") ?? "").trim();
      if (!text || NO_REPLY_TEXTS.has(text)) return;
      const piece: AssistantText = { id: `${uuid}:${index}`, text, ...(timestamp ? { timestamp } : {}) };
      segment.trailing.push(piece);
      if (!segment.longest || text.length > segment.longest.text.length) segment.longest = piece;
    });
    if (message.stop_reason === "end_turn" || message.stop_reason === "stop_sequence") segment.settled = true;
  }

  private startSegment(id: string): void {
    this.closeSegment();
    this.segmentCount += 1;
    this.segment = { id: `${id}#${this.segmentCount}`, trailing: [], settled: false, started: false };
  }

  private closeSegment(): void {
    if (!this.segment) return;
    const reply = this.replyOf(this.segment, true);
    if (reply) this.finished.push(reply);
    this.segment = null;
  }

  /**
   * The reply a segment shows. A settled turn shows the text it ended on.
   * A turn cut off before settling (interrupted, or the captain spoke
   * mid-turn) shows its longest text only if that text is substantive;
   * short progress notes never surface.
   */
  private replyOf(segment: Segment, closed: boolean): ConversationMessage | null {
    let pieces: AssistantText[] = [];
    if (segment.settled && segment.trailing.length > 0) pieces = segment.trailing;
    else if (closed && segment.longest && segment.longest.text.length >= SUBSTANTIVE_CHARS) pieces = [segment.longest];
    if (pieces.length === 0) return null;
    const last = pieces[pieces.length - 1]!;
    return {
      id: `reply:${segment.id}`,
      role: "assistant",
      text: pieces.map((piece) => piece.text).join("\n\n"),
      ...(last.timestamp ? { timestamp: last.timestamp } : {}),
    };
  }

  snapshot(): ConversationSnapshot {
    const messages = [...this.finished];
    const open = this.segment;
    const reply = open ? this.replyOf(open, false) : null;
    if (reply) messages.push(reply);
    const lastIsUser = this.finished.length > 0 && this.finished[this.finished.length - 1]!.role === "user";
    const working = open !== null && !reply && (open.started || lastIsUser);
    return { messages, working, ...(this.lastActivity ? { lastActivity: this.lastActivity } : {}) };
  }
}

/** Convenience for whole-file reads and tests. */
export function conversationFromLines(lines: Iterable<string>): ConversationSnapshot {
  const conversation = new TranscriptConversation();
  for (const line of lines) if (line.trim()) conversation.pushLine(line);
  return conversation.snapshot();
}
