import type pg from "pg";

// Operational runtime schema, owned by TypeScript Core. Mirrors the legacy
// Rails tables (db/schema.rb) exactly for the tables the runtime reads or
// writes, so a fresh machine needs no Rails db:prepare. Idempotent: safe to
// run on every pool. CREATE TABLE IF NOT EXISTS never alters an existing
// table; the legacy Rails tree stays authoritative for migrations.
export const RUNTIME_SCHEMA_STATEMENTS: readonly string[] = [
  `CREATE TABLE IF NOT EXISTS projects (
    id bigserial PRIMARY KEY,
    name varchar,
    description text,
    root_path varchar,
    archived_at timestamp(6) without time zone,
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL
  )`,
  `CREATE INDEX IF NOT EXISTS index_projects_on_archived_at ON projects (archived_at)`,
  `CREATE UNIQUE INDEX IF NOT EXISTS index_projects_on_name ON projects (name)`,

  `CREATE TABLE IF NOT EXISTS agent_tasks (
    id bigserial PRIMARY KEY,
    project_id bigint NOT NULL REFERENCES projects(id),
    task_key varchar NOT NULL,
    status varchar DEFAULT 'awaiting_grant' NOT NULL,
    intended_outcome text NOT NULL,
    success_criteria jsonb DEFAULT '[]'::jsonb NOT NULL,
    verification_criteria jsonb DEFAULT '[]'::jsonb NOT NULL,
    plan jsonb DEFAULT '{}'::jsonb NOT NULL,
    context_snapshot jsonb DEFAULT '{}'::jsonb NOT NULL,
    repository_snapshot jsonb DEFAULT '{}'::jsonb NOT NULL,
    recommended_next_action text,
    outcome_summary text,
    verification_result jsonb DEFAULT '{}'::jsonb NOT NULL,
    revision bigint DEFAULT 0 NOT NULL,
    started_at timestamp(6) without time zone,
    completed_at timestamp(6) without time zone,
    cancelled_at timestamp(6) without time zone,
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    CONSTRAINT agent_tasks_revision_check CHECK (revision >= 0),
    CONSTRAINT agent_tasks_status_check CHECK (status::text = ANY (ARRAY['awaiting_grant','ready','running','blocked','completed','failed','cancelled']::text[]))
  )`,
  `CREATE INDEX IF NOT EXISTS index_agent_tasks_on_project_id ON agent_tasks (project_id)`,
  `CREATE UNIQUE INDEX IF NOT EXISTS index_agent_tasks_one_unfinished_per_project ON agent_tasks (project_id) WHERE status::text = ANY (ARRAY['awaiting_grant','ready','running','blocked']::text[])`,
  `CREATE UNIQUE INDEX IF NOT EXISTS index_agent_tasks_on_task_key ON agent_tasks (task_key)`,

  `CREATE TABLE IF NOT EXISTS task_grants (
    id bigserial PRIMARY KEY,
    agent_task_id bigint NOT NULL REFERENCES agent_tasks(id),
    grant_key varchar NOT NULL,
    status varchar DEFAULT 'proposed' NOT NULL,
    scope_digest varchar NOT NULL,
    repository_roots jsonb DEFAULT '[]'::jsonb NOT NULL,
    worktree_paths jsonb DEFAULT '[]'::jsonb NOT NULL,
    worker_adapters jsonb DEFAULT '[]'::jsonb NOT NULL,
    file_operations jsonb DEFAULT '[]'::jsonb NOT NULL,
    command_classes jsonb DEFAULT '[]'::jsonb NOT NULL,
    verification_commands jsonb DEFAULT '[]'::jsonb NOT NULL,
    renewal_required_actions jsonb DEFAULT '[]'::jsonb NOT NULL,
    max_concurrency integer DEFAULT 1 NOT NULL,
    budget jsonb DEFAULT '{}'::jsonb NOT NULL,
    approved_at timestamp(6) without time zone,
    expires_at timestamp(6) without time zone NOT NULL,
    ended_at timestamp(6) without time zone,
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    provider_identity varchar DEFAULT 'opencode-configured-provider' NOT NULL,
    decision_reason text,
    decided_at timestamp(6) without time zone,
    external_roots jsonb DEFAULT '[]'::jsonb NOT NULL,
    CONSTRAINT task_grants_concurrency_check CHECK (max_concurrency > 0),
    CONSTRAINT task_grants_status_check CHECK (status::text = ANY (ARRAY['proposed','approved','expired','revoked','exhausted','completed']::text[]))
  )`,
  `CREATE INDEX IF NOT EXISTS index_task_grants_on_agent_task_id ON task_grants (agent_task_id)`,
  `CREATE UNIQUE INDEX IF NOT EXISTS index_task_grants_one_approved_per_task ON task_grants (agent_task_id) WHERE status::text = 'approved'`,
  `CREATE UNIQUE INDEX IF NOT EXISTS index_task_grants_on_grant_key ON task_grants (grant_key)`,

  `CREATE TABLE IF NOT EXISTS task_assignments (
    id bigserial PRIMARY KEY,
    agent_task_id bigint NOT NULL REFERENCES agent_tasks(id),
    assignment_key varchar NOT NULL,
    status varchar DEFAULT 'pending' NOT NULL,
    title varchar NOT NULL,
    instructions text NOT NULL,
    success_criteria jsonb DEFAULT '[]'::jsonb NOT NULL,
    capability_requirements jsonb DEFAULT '[]'::jsonb NOT NULL,
    dependency_keys jsonb DEFAULT '[]'::jsonb NOT NULL,
    declared_file_scope jsonb DEFAULT '[]'::jsonb NOT NULL,
    excluded_adapters jsonb DEFAULT '[]'::jsonb NOT NULL,
    worktree_path varchar,
    branch_name varchar,
    base_head varchar,
    verification_result jsonb DEFAULT '{}'::jsonb NOT NULL,
    integration_result jsonb DEFAULT '{}'::jsonb NOT NULL,
    revision bigint DEFAULT 1 NOT NULL,
    started_at timestamp(6) without time zone,
    ended_at timestamp(6) without time zone,
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    repository_root text NOT NULL,
    CONSTRAINT task_assignments_revision_check CHECK (revision > 0),
    CONSTRAINT task_assignments_status_check CHECK (status::text = ANY (ARRAY['pending','running','verified','blocked','integrated','failed','cancelled']::text[]))
  )`,
  `CREATE INDEX IF NOT EXISTS index_task_assignments_on_task_and_repository ON task_assignments (agent_task_id, repository_root)`,
  `CREATE INDEX IF NOT EXISTS index_task_assignments_on_agent_task_id_and_status ON task_assignments (agent_task_id, status)`,
  `CREATE INDEX IF NOT EXISTS index_task_assignments_on_agent_task_id ON task_assignments (agent_task_id)`,
  `CREATE UNIQUE INDEX IF NOT EXISTS index_task_assignments_on_assignment_key ON task_assignments (assignment_key)`,

  `CREATE TABLE IF NOT EXISTS worker_sessions (
    id bigserial PRIMARY KEY,
    agent_task_id bigint NOT NULL REFERENCES agent_tasks(id),
    task_grant_id bigint NOT NULL REFERENCES task_grants(id),
    resumes_worker_session_id bigint REFERENCES worker_sessions(id),
    worker_key varchar NOT NULL,
    status varchar DEFAULT 'queued' NOT NULL,
    adapter varchar NOT NULL,
    executable_path varchar,
    executable_version varchar,
    working_directory varchar NOT NULL,
    external_session_id varchar,
    process_id bigint,
    assignment_revision integer DEFAULT 1 NOT NULL,
    last_heartbeat_at timestamp(6) without time zone,
    started_at timestamp(6) without time zone,
    ended_at timestamp(6) without time zone,
    exit_status integer,
    error_summary text,
    output text,
    usage jsonb DEFAULT '{}'::jsonb NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    task_assignment_id bigint NOT NULL REFERENCES task_assignments(id),
    capabilities jsonb DEFAULT '[]'::jsonb NOT NULL,
    last_observed_at timestamp(6) without time zone,
    stop_reason text,
    process_identity varchar,
    process_group_id bigint,
    CONSTRAINT worker_sessions_status_check CHECK (status::text = ANY (ARRAY['queued','starting','running','stopping','completed','failed','interrupted','cancelled','stopped','replaced']::text[]))
  )`,
  `CREATE INDEX IF NOT EXISTS index_worker_sessions_on_agent_task_id ON worker_sessions (agent_task_id)`,
  `CREATE INDEX IF NOT EXISTS index_worker_sessions_on_resumes_worker_session_id ON worker_sessions (resumes_worker_session_id)`,
  `CREATE INDEX IF NOT EXISTS index_worker_sessions_on_task_assignment_id ON worker_sessions (task_assignment_id)`,
  `CREATE UNIQUE INDEX IF NOT EXISTS index_worker_sessions_one_live_per_assignment ON worker_sessions (task_assignment_id) WHERE status::text = ANY (ARRAY['queued','starting','running','stopping']::text[])`,
  `CREATE INDEX IF NOT EXISTS index_worker_sessions_on_task_grant_id ON worker_sessions (task_grant_id)`,
  `CREATE UNIQUE INDEX IF NOT EXISTS index_worker_sessions_on_worker_key ON worker_sessions (worker_key)`,

  `CREATE TABLE IF NOT EXISTS worker_commands (
    id bigserial PRIMARY KEY,
    agent_task_id bigint NOT NULL REFERENCES agent_tasks(id),
    worker_session_id bigint NOT NULL REFERENCES worker_sessions(id),
    command_key varchar NOT NULL,
    kind varchar NOT NULL,
    status varchar DEFAULT 'queued' NOT NULL,
    idempotency_key varchar NOT NULL,
    payload jsonb DEFAULT '{}'::jsonb NOT NULL,
    dispatched_at timestamp(6) without time zone,
    completed_at timestamp(6) without time zone,
    error_summary text,
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    CONSTRAINT worker_commands_kind_check CHECK (kind::text = ANY (ARRAY['stop','retry','redirect','replace']::text[])),
    CONSTRAINT worker_commands_status_check CHECK (status::text = ANY (ARRAY['queued','dispatched','completed','failed','cancelled']::text[]))
  )`,
  `CREATE INDEX IF NOT EXISTS index_worker_commands_on_agent_task_id ON worker_commands (agent_task_id)`,
  `CREATE UNIQUE INDEX IF NOT EXISTS index_worker_commands_on_command_key ON worker_commands (command_key)`,
  `CREATE UNIQUE INDEX IF NOT EXISTS index_worker_commands_on_idempotency_key ON worker_commands (idempotency_key)`,
  `CREATE INDEX IF NOT EXISTS index_worker_commands_on_worker_session_id_and_status ON worker_commands (worker_session_id, status)`,
  `CREATE INDEX IF NOT EXISTS index_worker_commands_on_worker_session_id ON worker_commands (worker_session_id)`,

  `CREATE TABLE IF NOT EXISTS task_sessions (
    id bigserial PRIMARY KEY,
    agent_task_id bigint NOT NULL REFERENCES agent_tasks(id),
    session_key varchar NOT NULL,
    status varchar DEFAULT 'active' NOT NULL,
    resumed boolean DEFAULT false NOT NULL,
    interpretation_status varchar DEFAULT 'pending' NOT NULL,
    manual_context_restatement boolean DEFAULT false NOT NULL,
    tool_escape boolean DEFAULT false NOT NULL,
    startup_snapshot jsonb DEFAULT '{}'::jsonb NOT NULL,
    started_at timestamp(6) without time zone NOT NULL,
    ended_at timestamp(6) without time zone,
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    CONSTRAINT task_sessions_interpretation_check CHECK (interpretation_status::text = ANY (ARRAY['pending','accepted','focused_corrected','replaced']::text[])),
    CONSTRAINT task_sessions_status_check CHECK (status::text = ANY (ARRAY['active','ended']::text[]))
  )`,
  `CREATE INDEX IF NOT EXISTS index_task_sessions_on_agent_task_id ON task_sessions (agent_task_id)`,
  `CREATE UNIQUE INDEX IF NOT EXISTS index_task_sessions_one_active_per_task ON task_sessions (agent_task_id) WHERE status::text = 'active'`,
  `CREATE UNIQUE INDEX IF NOT EXISTS index_task_sessions_on_session_key ON task_sessions (session_key)`,

  `CREATE TABLE IF NOT EXISTS task_artifacts (
    id bigserial PRIMARY KEY,
    agent_task_id bigint NOT NULL REFERENCES agent_tasks(id),
    task_assignment_id bigint REFERENCES task_assignments(id),
    worker_session_id bigint REFERENCES worker_sessions(id),
    artifact_key varchar NOT NULL,
    kind varchar NOT NULL,
    title varchar NOT NULL,
    media_type varchar NOT NULL,
    byte_size bigint NOT NULL,
    sha256_digest varchar NOT NULL,
    verification_status varchar DEFAULT 'pending' NOT NULL,
    source_revision bigint NOT NULL,
    content text,
    relative_path varchar,
    repository_head varchar,
    provenance jsonb DEFAULT '{}'::jsonb NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    CONSTRAINT task_artifacts_byte_size_check CHECK (byte_size >= 0),
    CONSTRAINT task_artifacts_kind_check CHECK (kind::text = ANY (ARRAY['diff','test','log','code','image','document']::text[])),
    CONSTRAINT task_artifacts_source_revision_check CHECK (source_revision >= 0),
    CONSTRAINT task_artifacts_verification_status_check CHECK (verification_status::text = ANY (ARRAY['pending','verified','rejected']::text[]))
  )`,
  `CREATE INDEX IF NOT EXISTS index_task_artifacts_on_agent_task_id_and_source_revision ON task_artifacts (agent_task_id, source_revision)`,
  `CREATE INDEX IF NOT EXISTS index_task_artifacts_on_agent_task_id ON task_artifacts (agent_task_id)`,
  `CREATE UNIQUE INDEX IF NOT EXISTS index_task_artifacts_on_artifact_key ON task_artifacts (artifact_key)`,
  `CREATE INDEX IF NOT EXISTS index_task_artifacts_on_task_assignment_id ON task_artifacts (task_assignment_id)`,
  `CREATE INDEX IF NOT EXISTS index_task_artifacts_on_worker_session_id ON task_artifacts (worker_session_id)`,

  `CREATE TABLE IF NOT EXISTS task_corrections (
    id bigserial PRIMARY KEY,
    agent_task_id bigint NOT NULL REFERENCES agent_tasks(id),
    supersedes_task_correction_id bigint REFERENCES task_corrections(id),
    correction_key varchar NOT NULL,
    original_claim text,
    corrected_value text NOT NULL,
    task_revision bigint NOT NULL,
    surface_revision bigint,
    authority varchar DEFAULT 'user' NOT NULL,
    provenance jsonb DEFAULT '{}'::jsonb NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    CONSTRAINT task_corrections_authority_check CHECK (authority::text = 'user'::text),
    CONSTRAINT task_corrections_surface_revision_check CHECK (surface_revision IS NULL OR surface_revision >= 0),
    CONSTRAINT task_corrections_revision_check CHECK (task_revision >= 0)
  )`,
  `CREATE UNIQUE INDEX IF NOT EXISTS index_task_corrections_on_agent_task_id_and_task_revision ON task_corrections (agent_task_id, task_revision)`,
  `CREATE INDEX IF NOT EXISTS index_task_corrections_on_agent_task_id ON task_corrections (agent_task_id)`,
  `CREATE UNIQUE INDEX IF NOT EXISTS index_task_corrections_on_correction_key ON task_corrections (correction_key)`,
  `CREATE INDEX IF NOT EXISTS index_task_corrections_on_supersedes_task_correction_id ON task_corrections (supersedes_task_correction_id)`,

  // surface_items is owned by the legacy surface subsystem, not the runtime.
  // The runtime only reads it (release-acceptance joins) and holds FKs to it,
  // so it is created here without its surfaces/scenes parents.
  `CREATE TABLE IF NOT EXISTS surface_items (
    id bigserial PRIMARY KEY,
    surface_id bigint NOT NULL,
    item_key varchar NOT NULL,
    kind varchar NOT NULL,
    intent varchar NOT NULL,
    renderer varchar NOT NULL,
    depth varchar DEFAULT 'middle' NOT NULL,
    state varchar DEFAULT 'presented' NOT NULL,
    title varchar NOT NULL,
    summary text,
    position integer DEFAULT 0 NOT NULL,
    context_refs jsonb DEFAULT '[]'::jsonb NOT NULL,
    source_refs jsonb DEFAULT '[]'::jsonb NOT NULL,
    actions jsonb DEFAULT '[]'::jsonb NOT NULL,
    relationships jsonb DEFAULT '[]'::jsonb NOT NULL,
    metadata jsonb DEFAULT '{}'::jsonb NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    scene_id bigint
  )`,
  `CREATE INDEX IF NOT EXISTS index_surface_items_on_scene_id ON surface_items (scene_id)`,
  `CREATE UNIQUE INDEX IF NOT EXISTS index_surface_items_on_surface_id_and_item_key ON surface_items (surface_id, item_key)`,
  `CREATE INDEX IF NOT EXISTS index_surface_items_on_surface_id_and_position ON surface_items (surface_id, position)`,
  `CREATE INDEX IF NOT EXISTS index_surface_items_on_surface_id ON surface_items (surface_id)`,

  `CREATE TABLE IF NOT EXISTS task_recommendations (
    id bigserial PRIMARY KEY,
    agent_task_id bigint NOT NULL REFERENCES agent_tasks(id),
    task_session_id bigint REFERENCES task_sessions(id),
    release_key varchar NOT NULL,
    task_revision bigint NOT NULL,
    action text NOT NULL,
    action_digest varchar NOT NULL,
    disposition varchar DEFAULT 'offered' NOT NULL,
    acted_at timestamp(6) without time zone,
    metadata jsonb DEFAULT '{}'::jsonb NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    surface_item_id bigint REFERENCES surface_items(id),
    action_id varchar,
    CONSTRAINT task_recommendations_disposition_check CHECK (disposition::text = ANY (ARRAY['offered','accepted','adapted','rejected']::text[])),
    CONSTRAINT task_recommendations_revision_check CHECK (task_revision >= 0),
    CONSTRAINT task_recommendations_source_check CHECK (task_session_id IS NOT NULL OR surface_item_id IS NOT NULL)
  )`,
  `CREATE INDEX IF NOT EXISTS index_task_recommendations_on_agent_task_id ON task_recommendations (agent_task_id)`,
  `CREATE INDEX IF NOT EXISTS index_task_recommendations_on_release_key_and_created_at ON task_recommendations (release_key, created_at)`,
  `CREATE INDEX IF NOT EXISTS index_task_recommendations_on_surface_item_id ON task_recommendations (surface_item_id)`,
  `CREATE UNIQUE INDEX IF NOT EXISTS idx_on_task_session_id_action_digest_7c697bc9ba ON task_recommendations (task_session_id, action_digest)`,
  `CREATE INDEX IF NOT EXISTS index_task_recommendations_on_task_session_id ON task_recommendations (task_session_id)`,

  `CREATE TABLE IF NOT EXISTS runtime_events (
    id bigserial PRIMARY KEY,
    agent_task_id bigint NOT NULL REFERENCES agent_tasks(id),
    task_grant_id bigint REFERENCES task_grants(id),
    worker_session_id bigint REFERENCES worker_sessions(id),
    event_key varchar NOT NULL,
    event_type varchar NOT NULL,
    idempotency_key varchar,
    task_revision bigint NOT NULL,
    payload jsonb DEFAULT '{}'::jsonb NOT NULL,
    occurred_at timestamp(6) without time zone NOT NULL,
    archive_delivered_at timestamp(6) without time zone,
    broadcast_delivered_at timestamp(6) without time zone,
    delivery_attempts integer DEFAULT 0 NOT NULL,
    next_delivery_at timestamp(6) without time zone,
    last_delivery_error text,
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL
  )`,
  `CREATE UNIQUE INDEX IF NOT EXISTS index_runtime_events_on_agent_task_id_and_task_revision ON runtime_events (agent_task_id, task_revision)`,
  `CREATE INDEX IF NOT EXISTS index_runtime_events_on_agent_task_id ON runtime_events (agent_task_id)`,
  `CREATE INDEX IF NOT EXISTS index_runtime_events_pending_archive ON runtime_events (archive_delivered_at, next_delivery_at)`,
  `CREATE UNIQUE INDEX IF NOT EXISTS index_runtime_events_on_event_key ON runtime_events (event_key)`,
  `CREATE UNIQUE INDEX IF NOT EXISTS index_runtime_events_on_idempotency_key ON runtime_events (idempotency_key) WHERE idempotency_key IS NOT NULL`,
  `CREATE INDEX IF NOT EXISTS index_runtime_events_on_task_grant_id ON runtime_events (task_grant_id)`,
  `CREATE INDEX IF NOT EXISTS index_runtime_events_on_worker_session_id ON runtime_events (worker_session_id)`,

  `CREATE TABLE IF NOT EXISTS runtime_delivery_receipts (
    id bigserial PRIMARY KEY,
    runtime_event_id bigint NOT NULL REFERENCES runtime_events(id),
    client_id varchar NOT NULL,
    surface_id bigint,
    acknowledged_at timestamp(6) without time zone NOT NULL,
    delivery_latency_ms integer NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    task_revision bigint NOT NULL,
    binding_digest varchar,
    surface_item_id bigint REFERENCES surface_items(id),
    CONSTRAINT runtime_delivery_receipts_latency_check CHECK (delivery_latency_ms >= 0),
    CONSTRAINT runtime_delivery_receipts_task_revision_check CHECK (task_revision >= 0)
  )`,
  `CREATE UNIQUE INDEX IF NOT EXISTS index_runtime_delivery_receipts_on_event_and_client ON runtime_delivery_receipts (runtime_event_id, client_id)`,
  `CREATE INDEX IF NOT EXISTS index_runtime_delivery_receipts_on_runtime_event_id ON runtime_delivery_receipts (runtime_event_id)`,
  `CREATE INDEX IF NOT EXISTS index_runtime_delivery_receipts_on_surface_item_id ON runtime_delivery_receipts (surface_item_id)`,

  `CREATE TABLE IF NOT EXISTS runtime_delivery_states (
    id bigserial PRIMARY KEY,
    listener_key varchar NOT NULL,
    last_event_id bigint DEFAULT 0 NOT NULL,
    lease_owner varchar,
    lease_expires_at timestamp(6) without time zone,
    last_received_at timestamp(6) without time zone,
    last_delivered_at timestamp(6) without time zone,
    delivery_latency_ms integer,
    last_error text,
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    CONSTRAINT runtime_delivery_states_latency_check CHECK (delivery_latency_ms IS NULL OR delivery_latency_ms >= 0),
    CONSTRAINT runtime_delivery_states_cursor_check CHECK (last_event_id >= 0)
  )`,
  `CREATE UNIQUE INDEX IF NOT EXISTS index_runtime_delivery_states_on_listener_key ON runtime_delivery_states (listener_key)`,

  `CREATE TABLE IF NOT EXISTS release_markers (
    id bigserial PRIMARY KEY,
    release_key varchar NOT NULL,
    available_at timestamp(6) without time zone NOT NULL,
    metadata jsonb DEFAULT '{}'::jsonb NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL
  )`,
  `CREATE UNIQUE INDEX IF NOT EXISTS index_release_markers_on_release_key ON release_markers (release_key)`,

  `CREATE TABLE IF NOT EXISTS release_acceptance_observations (
    id bigserial PRIMARY KEY,
    kind varchar NOT NULL,
    passed boolean NOT NULL,
    evidence jsonb DEFAULT '{}'::jsonb NOT NULL,
    idempotency_key varchar NOT NULL,
    observed_at timestamp(6) without time zone NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    CONSTRAINT release_acceptance_observations_kind_check CHECK (kind::text = ANY (ARRAY['memory_safety','recommendation_rationale','automated_acceptance']::text[]))
  )`,
  `CREATE UNIQUE INDEX IF NOT EXISTS index_release_acceptance_observations_on_idempotency_key ON release_acceptance_observations (idempotency_key)`,
  `CREATE INDEX IF NOT EXISTS index_release_acceptance_observations_on_kind_and_observed_at ON release_acceptance_observations (kind, observed_at)`,
];

const schemaReady = new WeakMap<pg.Pool, Promise<void>>();

// `rawQuery` must bypass the pool's own bootstrap wrapper or this recurses.
export function ensureRuntimeSchema(
  pool: pg.Pool,
  rawQuery: (sql: string) => Promise<unknown> = (sql) => pool.query(sql),
): Promise<void> {
  const existing = schemaReady.get(pool);
  if (existing) return existing;
  const ready = runRuntimeSchema(rawQuery).catch((error) => {
    schemaReady.delete(pool);
    throw error;
  });
  schemaReady.set(pool, ready);
  return ready;
}

async function runRuntimeSchema(rawQuery: (sql: string) => Promise<unknown>): Promise<void> {
  for (const statement of RUNTIME_SCHEMA_STATEMENTS) {
    await rawQuery(statement);
  }
}
