import { existsSync, mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { afterEach, beforeEach, describe, expect, it } from "vitest";
import { renderTastePage } from "../../conversation-view/taste-page.js";
import type { Project } from "../projects.js";
import { TASTE_PRINCIPLES } from "../taste-principles.js";
import { installTasteSkills, isDurable, planTasteSkills, renderTasteSkill, syncTasteSkills, tasteSkillKind } from "../taste-skills.js";
import { applyTasteOps, readTaste, ruleId, vetoRule, writeTaste, type TasteProfile, type TasteRule } from "../taste.js";

const project = (id: string, name: string, repos: string[] = []): Project =>
  ({ id, name, repos, what: "", kind: "client", status: "active", now: "" }) as unknown as Project;
const CAPFIVE = project("capfive-client-work", "Capfive client work", ["/Users/george/Documents/cap5"]);
const GNM = project("gnm-good-neighbours-market", "GNM (Good Neighbours Market)", ["/Users/george/Documents/good_neighbours"]);
const FLYD = project("flyd", "Flyd", ["/Users/george/Documents/flyd"]);
const PROJECTS = [CAPFIVE, GNM, FLYD];

let dir: string;
let roots: string[];
beforeEach(() => {
  dir = mkdtempSync(join(tmpdir(), "flyd-taste-skills-"));
  process.env.FLYD_TASTE_FILE = join(dir, "TASTE.md");
  process.env.FLYD_TASTE_STATE = join(dir, "taste-state.json");
  process.env.FLYD_PROJECTS_PATH = join(dir, "projects.json");
  writeFileSync(process.env.FLYD_PROJECTS_PATH, JSON.stringify({ projects: PROJECTS }));
  roots = [join(dir, "claude-skills"), join(dir, "agents-skills")];
});
afterEach(() => {
  delete process.env.FLYD_TASTE_SKILLS;
  rmSync(dir, { recursive: true, force: true });
});

const rule = (text: string, count: number, scope = "personal", extra: Partial<TasteRule> = {}): TasteRule => ({
  id: ruleId(text), text, scope, count, projects: scope === "personal" ? [] : [scope], last: "2026-10-06",
  evidence: [{ quote: text.toLowerCase(), source: "Claude Code", date: "2026-10-06" }], ...extra,
});

function learned(): TasteProfile {
  return {
    rules: [
      rule("Headlines should be much bigger — large, bold headline type.", 4),
      rule("Buttons need clear padding above them.", 2),
      rule("The cube should also rotate slowly.", 1),
      rule("Default to working locally rather than on branches.", 3),
      rule("Mobile header ledes use line-height 1.24.", 3, "capfive-client-work"),
      rule("Deal cards share the same bottom y position.", 2, "capfive-client-work"),
      rule("Our Network eyebrow is 1.4em.", 1, "capfive-client-work"),
      rule("Voice with no text box selected goes to the clipboard.", 2, "flyd"),
    ],
    vetoed: [],
    names: { "capfive-client-work": "Capfive client work", "gnm-good-neighbours-market": "GNM (Good Neighbours Market)", flyd: "Flyd" },
  };
}

const read = (root: string, name: string) => readFileSync(join(root, name, "SKILL.md"), "utf8");

describe("taste skills: generation", () => {
  it("compiles his principles and durable rules into standard skills that load for UI work and keep his words", () => {
    writeTaste(learned());
    const sync = syncTasteSkills({ roots, projects: PROJECTS });
    expect(sync.seeded).toBe(TASTE_PRINCIPLES.length);
    expect(sync.skills).toEqual(["flyd-taste-interface", "flyd-taste-spacing", "flyd-taste-capfive-client-work", "flyd-taste-gnm-good-neighbours-market"]);

    const ui = read(roots[0]!, "flyd-taste-interface");
    expect(ui).toMatch(/^---\nname: flyd-taste-interface\ndescription: ".*UI, layout, visual, CSS, front-end or design work.*before reporting done\."\n---\n<!-- flyd-taste-skill: generated by Flyd/);
    expect(ui).toContain("Do not hand-edit: edit TASTE.md, or say \"not me\"");
    expect(ui).toContain("Before you report the work done, check it against every rule below");
    expect(ui).toContain("## His principles");
    expect(ui).toContain("- **A screen, not a page");
    expect(ui).toContain('  - "we have a scrolling page! not a "Macromedia Flash" screen interface. this still feels like a website" — Codex, Flyd, 2026-07-14');
    expect(ui).toContain("- **Headlines should be much bigger — large, bold headline type.** (seen 4×)");

    const spacing = read(roots[1]!, "flyd-taste-spacing");
    expect(spacing).toContain("more balanced spacing between text elements");
    expect(spacing).toContain("- **Buttons need clear padding above them.** (seen 2×)");
    expect(spacing).not.toContain("Headlines should be much bigger");

    // A project skill names its repo, and holds there alone.
    const capfive = read(roots[0]!, "flyd-taste-capfive-client-work");
    expect(capfive).toContain("Use only when the working directory is inside /Users/george/Documents/cap5; do not load it anywhere else");
    expect(capfive).toContain("Mobile header ledes use line-height 1.24.");
    const gnm = read(roots[0]!, "flyd-taste-gnm-good-neighbours-market");
    expect(gnm).toContain("every section should be 100vh");
    expect(gnm).not.toContain("line-height 1.24");
    expect(capfive).not.toContain("100vh");
  });

  it("leaves one-off trivia, rules about process and thin projects out of every skill", () => {
    const profile = learned();
    const skills = planTasteSkills(profile, PROJECTS);
    const carried = skills.flatMap((skill) => [...skill.principles, ...skill.rules].map((item) => item.text));
    expect(carried).not.toContain("The cube should also rotate slowly.");
    expect(carried).not.toContain("Our Network eyebrow is 1.4em.");
    expect(carried).not.toContain("Default to working locally rather than on branches.");
    // One durable Flyd rule is not enough for a project skill of its own.
    expect(skills.map((skill) => skill.name)).not.toContain("flyd-taste-flyd");
    expect(isDurable(rule("Seen once.", 1))).toBe(false);
    expect(isDurable(rule("Written by George.", 0))).toBe(true);
    expect(isDurable(rule("A principle.", 1, "personal", { principle: true }))).toBe(true);
    expect(tasteSkillKind(rule("Equal side padding on both edges.", 3))).toBe("spacing");
    expect(tasteSkillKind(rule("No shadows on icon boxes.", 3))).toBe("interface");
    expect(tasteSkillKind(rule("Default to working locally.", 3))).toBeNull();
  });

  it("quotes only his words: no paraphrase is attributed to him", () => {
    const quotes = TASTE_PRINCIPLES.flatMap((seed) => seed.evidence.map((item) => item.quote.toLowerCase()));
    expect(quotes.some((quote) => quote.includes("flash-era"))).toBe(false);
    expect(quotes.some((quote) => quote.includes("motion as the interface"))).toBe(false);
    for (const seed of TASTE_PRINCIPLES) expect(seed.evidence.length).toBeGreaterThan(0);
  });
});

describe("taste skills: install", () => {
  it("is idempotent: a second sync seeds nothing and rewrites nothing", () => {
    writeTaste(learned());
    const first = syncTasteSkills({ roots, projects: PROJECTS });
    expect(first.written).toHaveLength(first.skills.length * roots.length);
    const taste = readFileSync(process.env.FLYD_TASTE_FILE!, "utf8");
    const second = syncTasteSkills({ roots, projects: PROJECTS });
    expect(second).toMatchObject({ seeded: 0, written: [], removed: [], refused: [], unchanged: first.written.length });
    expect(readFileSync(process.env.FLYD_TASTE_FILE!, "utf8")).toBe(taste);
  });

  it("never clobbers a skill Flyd did not generate, and removes its own when it has nothing left to say", () => {
    const theirs = join(roots[0]!, "flyd-taste-interface", "SKILL.md");
    mkdirSync(join(roots[0]!, "flyd-taste-interface"), { recursive: true });
    writeFileSync(theirs, "---\nname: flyd-taste-interface\ndescription: mine\n---\nHand written.\n");
    const handMade = join(roots[0]!, "flyd-taste-notes", "SKILL.md");
    mkdirSync(join(roots[0]!, "flyd-taste-notes"), { recursive: true });
    writeFileSync(handMade, "---\nname: flyd-taste-notes\ndescription: mine\n---\n");
    writeTaste(learned());
    const sync = syncTasteSkills({ roots, projects: PROJECTS });
    expect(sync.refused).toEqual([theirs]);
    expect(readFileSync(theirs, "utf8")).toContain("Hand written.");
    expect(existsSync(join(roots[1]!, "flyd-taste-interface", "SKILL.md"))).toBe(true);
    expect(readFileSync(handMade, "utf8")).toContain("mine");

    // CapFive's rules go; its generated skill goes with them. Nothing else is touched.
    const profile = readTaste();
    profile.rules = profile.rules.filter((item) => item.scope !== "capfive-client-work");
    writeTaste(profile);
    const after = syncTasteSkills({ roots, projects: PROJECTS });
    expect(after.removed).toEqual(roots.map((root) => join(root, "flyd-taste-capfive-client-work", "SKILL.md")));
    expect(existsSync(join(roots[0]!, "flyd-taste-capfive-client-work"))).toBe(false);
    expect(readFileSync(handMade, "utf8")).toContain("mine");
  });

  it("refuses to write into a folder of the same name that holds someone else's files", () => {
    const folder = join(roots[0]!, "flyd-taste-spacing");
    mkdirSync(folder, { recursive: true });
    writeFileSync(join(folder, "notes.md"), "mine");
    const receipt = installTasteSkills([{ name: "flyd-taste-spacing", content: "x" }], [roots[0]!]);
    expect(receipt.refused).toEqual([join(folder, "SKILL.md")]);
    expect(existsSync(join(folder, "SKILL.md"))).toBe(false);
  });

  it("seeds each principle once: one George deletes or vetoes is never brought back", () => {
    writeTaste(learned());
    syncTasteSkills({ roots, projects: PROJECTS });
    const prose = ruleId("Talk to him in prose, not bullet points.");
    const screen = ruleId(TASTE_PRINCIPLES[0]!.text);
    const profile = readTaste();
    profile.rules = profile.rules.filter((item) => item.id !== prose);
    writeTaste(profile);
    expect(vetoRule(screen)).toBe(true);
    const sync = syncTasteSkills({ roots, projects: PROJECTS });
    expect(sync.seeded).toBe(0);
    expect(readTaste().rules.map((item) => item.id)).not.toContain(prose);
    const ui = read(roots[0]!, "flyd-taste-interface");
    expect(ui).not.toContain("prose, not bullet points");
    expect(ui).not.toContain("A screen, not a page");
  });

  it("stays off when FLYD_TASTE_SKILLS=0, and never writes to the real home under test", () => {
    process.env.FLYD_TASTE_SKILLS = "0";
    expect(syncTasteSkills({ roots })).toMatchObject({ skipped: "disabled", written: [] });
    delete process.env.FLYD_TASTE_SKILLS;
    expect(syncTasteSkills()).toMatchObject({ skipped: "test", written: [] });
    expect(existsSync(process.env.FLYD_TASTE_FILE!)).toBe(false);
  });
});

describe("the Librarian decides what is his and what is one project's", () => {
  it("moves an Everywhere rule to the one project it belongs to, never one seen elsewhere or a principle", () => {
    const profile = learned();
    const capfiveWords = rule("Contact links scroll down to the form on the contact page.", 2);
    const seenTwice = rule("Edge spacing is symmetrical.", 6, "personal", { projects: ["capfive-client-work", "flyd"] });
    const principle = rule("A screen, not a page.", 3, "personal", { principle: true });
    profile.rules.push(capfiveWords, seenTwice, principle);
    const receipt = applyTasteOps(profile, [
      { op: "demote", id: capfiveWords.id, project: "capfive-client-work" },
      { op: "demote", id: seenTwice.id, project: "capfive-client-work" },
      { op: "demote", id: principle.id, project: "flyd" },
      { op: "demote", id: ruleId("Buttons need clear padding above them."), project: "nowhere" },
      { op: "retire", id: principle.id },
    ]);
    expect(receipt).toMatchObject({ demoted: 1, retired: 0 });
    expect(receipt.rejected).toHaveLength(4);
    expect(capfiveWords).toMatchObject({ scope: "capfive-client-work", projects: ["capfive-client-work"] });
    expect(seenTwice.scope).toBe("personal");
    expect(principle.scope).toBe("personal");
    // The move shows up in the skills: it now loads only in CapFive's repo.
    const skills = planTasteSkills(profile, PROJECTS);
    expect(skills.find((skill) => skill.name === "flyd-taste-capfive-client-work")?.rules.map((item) => item.id)).toContain(capfiveWords.id);
    expect(skills.find((skill) => skill.name === "flyd-taste-interface")?.rules.map((item) => item.id) ?? []).not.toContain(capfiveWords.id);
  });

  it("round-trips a principle and its skill through TASTE.md", () => {
    const profile = learned();
    profile.rules.push(rule("Balanced spacing between text elements.", 3, "personal", { principle: true, skill: "spacing" }));
    writeTaste(profile);
    expect(readTaste().rules.find((item) => item.text === "Balanced spacing between text elements.")).toMatchObject({ principle: true, skill: "spacing" });
    expect(renderTasteSkill(planTasteSkills(readTaste(), PROJECTS)[1]!, readTaste())).toContain("Balanced spacing between text elements.");
  });
});

describe("the taste page", () => {
  it("leads with the principles and skills, keeps each project short, and tucks the rest away", () => {
    writeTaste(learned());
    syncTasteSkills({ roots, projects: PROJECTS });
    const page = renderTastePage(readTaste(), { token: "t", projects: PROJECTS });
    const you = page.indexOf("You, everywhere");
    const capfive = page.indexOf("<h2>Capfive client work</h2>");
    const rest = page.indexOf('<details class="rest">');
    expect(you).toBeGreaterThan(-1);
    expect(capfive).toBeGreaterThan(you);
    expect(rest).toBeGreaterThan(capfive);
    expect(page.indexOf("A screen, not a page")).toBeLessThan(capfive);
    expect(page).toContain("flyd-taste-interface");
    expect(page).toContain("Loads only when working in /Users/george/Documents/cap5. Never anywhere else.");
    // Trivia and process rules live behind the quiet control only.
    expect(page.indexOf("The cube should also rotate slowly.")).toBeGreaterThan(rest);
    expect(page.indexOf("Default to working locally rather than on branches.")).toBeGreaterThan(rest);
    expect(page).toContain('data-action="veto"');
    expect(page).toContain('data-action="edit"');
  });
});
