import { readFileSync } from "node:fs";
import { describe, expect, it } from "vitest";
import { cleanCaptainText, conversationFromLines, TranscriptConversation } from "../transcript-filter.js";
import {
  apiError,
  assistantText,
  attachment,
  captain,
  captainBlocks,
  compactSummary,
  injection,
  legacyCaptain,
  metaUser,
  queuedCaptain,
  sidechain,
  thinking,
  title,
  toolResult,
  toolUse,
} from "./transcript-fixture.js";

const FINAL_REPLY = "Captain, the menu bar now sits 10px higher on every page. It's committed, not pushed.";

function visible(lines: string[]): Array<[string, string]> {
  return conversationFromLines(lines).messages.map((message) => [message.role, message.text]);
}

describe("transcript filter", () => {
  it("keeps only the captain's words and the reply he reads from a noisy turn", () => {
    const lines = [
      title("Menu bar position"),
      attachment({ type: "hook_success", hookName: "SessionStart:startup", content: "CAVEMAN MODE ACTIVE" }),
      attachment({ type: "hook_additional_context", content: ["## Today\nMonday"] }),
      attachment({ type: "total_tokens_reminder", text: "<total_tokens>15000000 tokens left</total_tokens>" }),
      captain("move the menubar up slightly"),
      thinking("The captain wants the header nudged; find the CSS."),
      toolUse("Grep", { pattern: "menubar" }),
      toolResult("wp-content/themes/capfive/style.css:120: .menubar { top: 32px }"),
      assistantText("Checking the header CSS now.", "tool_use"),
      toolUse("Edit"),
      toolResult("The file has been updated."),
      attachment({ type: "silent_turn_reminder", text: "The user hasn't heard from you in a while" }),
      assistantText("Edit in; verifying in the browser.", "tool_use"),
      toolUse("Bash", { command: "chrome-devtools-axi screenshot /tmp/a.png" }),
      toolResult("screenshot: /tmp/a.png"),
      assistantText(FINAL_REPLY),
    ];
    expect(visible(lines)).toEqual([
      ["user", "move the menubar up slightly"],
      ["assistant", FINAL_REPLY],
    ]);
  });

  it("drops hook, system, skill-body, command-output and compact injections", () => {
    const lines = [
      metaUser("Base directory for this skill: /Users/x/.claude/skills/poteto-mode\n\n# Poteto mode"),
      metaUser("<local-command-caveat>Caveat: The messages below were generated by the user while running local commands.</local-command-caveat>"),
      captain("<command-name>/clear</command-name>\n<command-message>clear</command-message>\n<command-args></command-args>"),
      legacyCaptain("<local-command-stdout></local-command-stdout>"),
      injection("<task-notification>\n<summary>Stop hook feedback</summary>\n</task-notification>\n<system-reminder>Stop hook blocking error</system-reminder>"),
      captain("<system-reminder>\nThe date has changed.\n</system-reminder>"),
      compactSummary("This session is being continued from a previous conversation that ran out of context."),
      captain("[Request interrupted by user for tool use]"),
      sidechain("subagent prompt: find all CSS files"),
      captain("push"),
      apiError("API Error: 529 overloaded"),
      toolUse("Bash", { command: "git push" }),
      toolResult("To github.com:x/y.git"),
      assistantText("Captain, pushed."),
    ];
    expect(visible(lines)).toEqual([
      ["user", "push"],
      ["assistant", "Captain, pushed."],
    ]);
  });

  it("shows a slash command the captain typed with words, as he typed it", () => {
    const text = "<command-message>design-review</command-message>\n<command-name>/design-review</command-name>\n<command-args>the graph could be prettier</command-args>";
    expect(cleanCaptainText(text)).toBe("/design-review the graph could be prettier");
  });

  it("strips reminders out of a real message and fences pasted content", () => {
    const text = 'for mobile 480 - \n\n<pasted_content id="43e0">\n.adviser h2 {\n  font-size: 4.2rem;\n}\n</pasted_content id="43e0">\n\n but smaller<system-reminder>ignore</system-reminder>';
    expect(cleanCaptainText(text)).toBe("for mobile 480 -\n\n```\n.adviser h2 {\n  font-size: 4.2rem;\n}\n```\n\nbut smaller");
  });

  it("accepts legacy entries without origin, and text-plus-image blocks", () => {
    const lines = [
      legacyCaptain("hello from an older build"),
      assistantText("Hello, Captain."),
      captainBlocks([{ type: "text", text: "[Image #12] mobile spacing is off" }, { type: "image", source: { type: "base64", media_type: "image/png", data: "AAAA" } }]),
      metaUser("[Image: source: /var/folders/clipboard.png]"),
      assistantText("Fixed the mobile spacing."),
    ];
    expect(visible(lines)).toEqual([
      ["user", "hello from an older build"],
      ["assistant", "Hello, Captain."],
      ["user", "[Image #12] mobile spacing is off"],
      ["assistant", "Fixed the mobile spacing."],
    ]);
  });

  it("includes messages the captain sent while the assistant was working", () => {
    const lines = [
      captain("menu text slightly smaller"),
      toolUse(),
      queuedCaptain("and make the footer padding less wide"),
      attachment({ type: "queued_command", prompt: "<task-notification>done</task-notification>", commandMode: "task-notification", origin: { kind: "task-notification" } }),
      toolUse(),
      toolResult("ok"),
      assistantText("Captain, both done: smaller menu text and a narrower footer."),
    ];
    expect(visible(lines)).toEqual([
      ["user", "menu text slightly smaller"],
      ["user", "and make the footer padding less wide"],
      ["assistant", "Captain, both done: smaller menu text and a narrower footer."],
    ]);
  });

  it("keeps a substantive reply from a turn cut off before it settled, but never short progress notes", () => {
    const report = `Captain, here is where the CapFive work stands. ${"The services page now matches the style guide and every section is wired to WordPress fields. ".repeat(4)}`;
    const lines = [
      captain("status?"),
      assistantText("Looking now.", "tool_use"),
      toolUse(),
      assistantText(report.trim(), "tool_use"),
      toolUse(),
      captain("never mind, push it"),
      assistantText("On it.", "tool_use"),
      toolUse(),
      captain("stop"),
      assistantText("Stopped."),
    ];
    expect(visible(lines)).toEqual([
      ["user", "status?"],
      ["assistant", report.trim()],
      ["user", "never mind, push it"],
      ["user", "stop"],
      ["assistant", "Stopped."],
    ]);
  });

  it("joins the trailing text blocks that end a turn", () => {
    const lines = [captain("what changed?"), toolUse(), assistantText("Two things changed:", null), assistantText("- the menu\n- the footer")];
    expect(visible(lines)).toEqual([
      ["user", "what changed?"],
      ["assistant", "Two things changed:\n\n- the menu\n- the footer"],
    ]);
  });

  it("says in a few plain words what the assistant is doing, without tool noise", () => {
    const conversation = new TranscriptConversation();
    conversation.pushLine(captain("fix the About cards"));
    expect(conversation.snapshot().activity).toBeUndefined();
    conversation.pushLine(toolUse("Bash", { command: "git status", description: "Check the working tree" }));
    expect(conversation.snapshot().activity).toBe("Check the working tree");
    // Reads and searches say nothing; the last step stays.
    conversation.pushLine(toolUse("Read", { file_path: "/x/about.css" }));
    expect(conversation.snapshot().activity).toBe("Check the working tree");
    conversation.pushLine(assistantText("Captain, **dispatching** a crewmate for the cards:", "tool_use"));
    conversation.pushLine(toolUse("Bash", { command: "fm-dispatch", description: "Launch crewmate" }));
    expect(conversation.snapshot().activity).toBe("Dispatching a crewmate for the cards");
    conversation.pushLine(toolUse("TodoWrite", { todos: [{ content: "Recolour cards", activeForm: "Recolouring the cards", status: "in_progress" }] }));
    expect(conversation.snapshot().activity).toBe("Recolouring the cards");
    conversation.pushLine(assistantText("Captain, the cards are navy again."));
    expect(conversation.snapshot()).toMatchObject({ working: false });
    expect(conversation.snapshot().activity).toBeUndefined();
  });

  it("never shows the assistant narrating itself as the current step", () => {
    const conversation = new TranscriptConversation();
    conversation.pushLine(captain("is CI green?"));
    for (const said of [
      "Let me check the CI run…",
      "One moment.",
      "I'll look at the logs.",
      "Passing this to the crew.",
      "I'm passing this to firstmate.",
      "Give me a moment.",
      "Still loading.",
      "Now routing this to the crew.",
      "I'm running the search tool now.",
    ]) {
      conversation.pushLine(assistantText(said, "tool_use"));
      conversation.pushLine(toolUse("Read", { file_path: "/x/ci.yml" }));
      expect(conversation.snapshot().activity).toBeUndefined();
    }
    conversation.pushLine(assistantText("Let me check the CI run…", "tool_use"));
    conversation.pushLine(toolUse("Bash", { command: "gh run list", description: "List CI runs" }));
    expect(conversation.snapshot().activity).toBe("List CI runs");
    conversation.pushLine(assistantText("Updating the calendar sync:", "tool_use"));
    conversation.pushLine(toolUse("Read", { file_path: "/x/sync.ts" }));
    expect(conversation.snapshot().activity).toBe("Updating the calendar sync");
  });

  it("reports working while a turn is open and settles when it ends", () => {
    const conversation = new TranscriptConversation();
    conversation.pushLine(captain("build the view"));
    expect(conversation.snapshot().working).toBe(true);
    conversation.pushLine(assistantText("Starting.", "tool_use"));
    conversation.pushLine(toolUse());
    expect(conversation.snapshot()).toMatchObject({ working: true });
    expect(conversation.snapshot().messages).toHaveLength(1);
    conversation.pushLine(assistantText("Captain, the view is up."));
    const settled = conversation.snapshot();
    expect(settled.working).toBe(false);
    expect(settled.messages.map((message) => message.text)).toEqual(["build the view", "Captain, the view is up."]);
    // Message ids stay stable across snapshots so the page can update in place.
    conversation.pushLine(captain("thanks"));
    expect(conversation.snapshot().messages.slice(0, 2).map((m) => m.id)).toEqual(settled.messages.map((m) => m.id));
  });

  it("reduces the demo session (used for the PR screenshot) to its seven human messages", () => {
    const lines = readFileSync(new URL("./fixtures/demo-session.jsonl", import.meta.url), "utf8").split("\n");
    const roles = conversationFromLines(lines).messages.map((message) => message.role);
    expect(roles).toEqual(["user", "assistant", "user", "user", "assistant", "user", "assistant"]);
    expect(conversationFromLines(lines).messages.some((message) => /Checking the crew|Sent to the onboarding/.test(message.text))).toBe(false);
  });

  it("ignores malformed and torn lines", () => {
    expect(visible(['{"type":"user","message":', "not json", captain("still here")])).toEqual([["user", "still here"]]);
  });
});
